from typing import Protocol
from uuid import UUID

from nexus_backend.catalog.domain.entities import Product


class ProductRepository(Protocol):
    async def list_all(self, skip: int = 0, limit: int = 50) -> list[Product]: ...
    async def get_by_id(self, product_id: UUID) -> Product | None: ...
    async def create(self, product: Product) -> Product: ...
    async def update(self, product: Product) -> Product: ...
    async def update_stock(self, product_id: UUID, quantity_delta: int) -> bool: ...
    async def search_by_vector(self, embedding: list[float], top_k: int = 5) -> list[Product]: ...
    async def get_without_embedding(self, limit: int = 100) -> list[Product]: ...
