from typing import Protocol
from uuid import UUID

from nexus_backend.cart.domain.entities import Cart


class CartRepository(Protocol):
    async def get_active_cart(self, user_id: UUID) -> Cart | None: ...
    async def get_or_create_cart(self, user_id: UUID) -> Cart: ...
    async def add_item(self, cart_id: UUID, product_id: UUID, quantity: int, unit_price: float) -> Cart: ...
    async def remove_item(self, cart_id: UUID, item_id: UUID) -> Cart: ...
    async def update_item_quantity(self, cart_id: UUID, item_id: UUID, quantity: int) -> Cart: ...
    async def checkout(self, cart_id: UUID) -> Cart: ...
